### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by ThaDaVos** [chabad360/cockpit-docker#3]
Cockpit version: 308-1~bpo23.04.1
Cockpit-docker version: 14
Docker version: 24.0.5
OS: Ubuntu 23.04

Does not load - after downloading the tar, extracting it and running "sudo make install" - it copied files to Cockpit, but it's not visible at all inside cockpit, not even after a machine reboot.

Steps to reproduce

1. Download tar
2. untar the download
3. run `sudo make install`
4. Restart cockpit

**Comment by chabad360** [comment]
It's possible you might not have installed the correct version accidentally. This port is a bit ramshakle in how I did it, so it's possible some stuff don't work fully (especially in the install process). I'll run through the steps you did later today and see what happens.

In general I would recommend installing the release packages instead of installing from source.

**Comment by chabad360** [comment]
Assuming this is fixed. Closing.
